### ISSUE TITLE
Create Dashboard component

### ISSUE THREAD

**Issue by gurunate** [gurunate/learning-portrait#114]
# Overview

Deliver a Dashboard component initially in Storybook.

## Acceptance Criteria

- Create a **Dashboard** component
  - Use [MUI Data Table](https://mui.com/material-ui/react-table/#data-table) 
  - props
    - `students`
    - `courses`
    - `sections`
    - `objectives`
    - `ratings`
- Update theme to match mock (below)
   
### Out-of-Scope

- Layout
  - header
  - footer
- Filters
  - courses
  - objectives 

### Mock

![Image](https://github.com/gurunate/learning-portrait/assets/742500/7c91245c-be61-41eb-81b9-55fbd8ecaae5)

https://www.figma.com/design/AnL18DKGLfAfbF7G0QdcfU/Learning-Portrait-2.0?node-id=3883-2804&t=rlxG7drYDQoFoPCh-4

**Comment by greenervigil** [comment]
Logic of Dashboard:

- Takes an array of courses (associated to the logged in user) to load the course dropdown options. Select the first course if there is no current saved last place.
- The initial course objectives is loaded to the objectives dropdown. 
- The course is then passed to the Course Table
- The Course Table takes that course data and builds out the columns for the table based on the objectives for the course
- The data loops through the students of the course to build out the rows
- For each student it must loop through their ratings and match the assessments objectiveId with the id of the objective associated to the columns and take the value to determine the Rating to display. 


Course Data 
```
export type Course = {
    id: string;
    name: string;
    description?: string;
    objectives?: Objective[];
    students?: Student[];
};
```

Objective Data 
```
export type Objective = {
    id: string;
    name: string;
    key: string;
    description?: string;
};
```

Student Data 
```
export type Student = User & {
    ratings?: Assessment[];
};
```

Assessment Data 
```
export type Assessment = {
    id: string;
    objectiveId: string;
    value: string;
    warning?: boolean;
    error?: boolean;
};
```

Potential saving of state

```
The standard auth/login pattern accepts a continue or next callback URL to redirect the user once authenticated.  That's usually the target URL of the resource you're attempting to access.  If that's empty, you default to the last URL help in local storage.  You'd keep updating that URL as the user moves around the site.```
