### ISSUE TITLE
Update MUI Theme to 8.2

### ISSUE THREAD

**Issue by gurunate** [gurunate/learning-portrait#128]
<img width="434" alt="image" src="https://github.com/gurunate/learning-portrait/assets/16470877/b1d8e4a3-8278-4e4c-94dc-6da7f8fad6f5">

Theme changes are located in the 8.1 tab.

**Comment by greenervigil** [comment]
@wartowski @gurunate Should we be using the NEW Styleguide for this?  It mostly consists of images.

**Comment by wartowski** [comment]
My understanding is yes, that Annie Rimbach added this in when doing version 8 to make things cleaner/easier.  @albonney - Am I remembering/stating correctly?
