### ISSUE TITLE
Add api.learningportrait.com DNS record

### ISSUE THREAD

**Issue by gurunate** [gurunate/learning-portrait#56]
```
cname.vercel-dns.com.
```

<img width="920" alt="image" src="https://github.com/gurunate/learning-portrait/assets/742500/c8f17582-f371-4aa9-b7ac-0f1125fb2003">

**Comment by wartowski** [comment]
added.  let me know if you need anything else.
 
<img width="1352" alt="image" src="https://github.com/gurunate/learning-portrait/assets/28845123/25e3771c-5356-47a8-8433-6425dded2b71">

**Comment by gurunate** [comment]
This is working.  Thanks @wartowski
